include_guard()

hunter_config(Boost
	URL "https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2"
	VERSION "1.87"
	SHA1 "acf19e9d53f0b6db8e85452978eb9c731ef8b865"
)

# BZip2 is used by PCRE2.
hunter_config(BZip2
	URL "https://github.com/Telefrag-Software/bzip2/archive/refs/heads/hunter-1.1.0.1.zip"
	VERSION "1.1.0.1"
	SHA1 "e5c848657e22f7e59165feee281b31aa15d2268d"
	CMAKE_ARGS
		ENABLE_APP=OFF
		ENABLE_TESTS=OFF
		ENABLE_DOCS=OFF
		ENABLE_EXAMPLES=OFF
		ENABLE_STATIC_LIB=ON
		ENABLE_SHARED_LIB=OFF
		ENABLE_STATIC_LIB_IS_PIC=ON
)

hunter_config(Catch2
	URL "https://codeload.github.com/catchorg/catch2/zip/tags/v3.5.0"
	VERSION "3.5.0.0"
	SHA1 "fd37a71ebf9455181a44fe7e2a0d56bb3c07b973"
	CMAKE_ARGS
		CATCH_INSTALL_DOCS=OFF
		CATCH_INSTALL_EXTRAS=ON
		CATCH_DEVELOPMENT_BUILD=OFF
		CATCH_ENABLE_REPRODUCIBLE_BUILD=ON
		CATCH_BUILD_TESTING=OFF
		CATCH_BUILD_EXAMPLES=OFF
		CATCH_BUILD_EXTRA_TESTS=OFF
		CATCH_BUILD_FUZZERS=OFF
		CATCH_BUILD_BENCHMARKS=OFF
		CATCH_ENABLE_COVERAGE=OFF
		CATCH_ENABLE_WERROR=ON
		CATCH_BUILD_SURROGATES=OFF
		CATCH_ENABLE_CONFIGURE_TESTS=OFF
		CATCH_ENABLE_CMAKE_HELPER_TESTS=OFF
)

hunter_config(expected-lite
	URL "https://codeload.github.com/nonstd-lite/expected-lite/zip/tags/v0.10.0"
	VERSION "0.10.0"
	SHA1 "0e44dae5a6de9fedcc1a281cec46d9e336a12b21"
	CMAKE_ARGS
		EXPECTED_LITE_OPT_BUILD_TESTS=OFF
		EXPECTED_LITE_OPT_BUILD_EXAMPLES=OFF
		EXPECTED_LITE_OPT_SELECT_STD=OFF
		EXPECTED_LITE_OPT_SELECT_NONSTD=OFF
)

hunter_config(fmt
	URL "https://codeload.github.com/fmtlib/fmt/zip/tags/12.1.0"
	VERSION "12.1.0"
	SHA1 "2d2580111a263b772bfbc266dbdfa902cb1a8bf9"
	CMAKE_ARGS
		FMT_PEDANTIC=OFF
		FMT_WERROR=OFF
		FMT_DOC=OFF
		FMT_INSTALL=ON
		FMT_TEST=OFF
		FMT_FUZZ=OFF
		FMT_CUDA_TEST=OFF
		FMT_OS=ON
		FMT_MODULE=OFF
		FMT_SYSTEM_HEADERS=OFF
		FMT_UNICODE=ON
)

hunter_config(llhttp
	URL "https://codeload.github.com/nodejs/llhttp/zip/tags/release/v9.3.1"
	VERSION "9.3.1"
	SHA1 "de76b20ad3cbd24e1b2ccb1d3393759b5a1304ea"
	CMAKE_ARGS
		LLHTTP_BUILD_SHARED_LIBS=OFF
		LLHTTP_BUILD_STATIC_LIBS=ON
)

hunter_config(pcre2
	URL "https://github.com/Telefrag-Software/pcre/archive/refs/heads/hunter-10.43.0.1.zip"
	VERSION "10.43.0.1"
	SHA1 "b6a4700010ff2c97239323842298b2efb8d2baac"
	CMAKE_ARGS
		BUILD_STATIC_LIBS=ON
		PCRE2_BUILD_PCRE2_8=ON
		PCRE2_BUILD_PCRE2_16=ON
		PCRE2_BUILD_PCRE2_32=ON
		PCRE2_STATIC_PIC=OFF
		PCRE2_REBUILD_CHARTABLES=OFF
		PCRE2_SHOW_REPORT=ON
		PCRE2_BUILD_PCRE2GREP=ON
		PCRE2_BUILD_TESTS=OFF
		NON_STANDARD_LIB_PREFIX=OFF
		NON_STANDARD_LIB_SUFFIX=OFF
		INSTALL_MSVC_PDB=ON
		PCRE2_SYMVERS=ON
		PCRE2_SUPPORT_LIBBZ2=ON
		PCRE2_SUPPORT_LIBZ=ON
		PCRE2_SUPPORT_LIBEDIT=OFF
		PCRE2_SUPPORT_LIBREADLINE=OFF
		PCRE2_SUPPORT_JIT=OFF
)

hunter_config(sobjectizer
	URL "https://github.com/Telefrag-Software/sobjectizer/archive/refs/heads/hunter-5.8.5.0.zip"
	VERSION "5.8.5.0"
	SHA1 "f67ade7b5df101181079f784048249b78e371ba3"
	CMAKE_ARGS
		BUILD_EXAMPLES=OFF
		BUILD_TESTS=OFF
		SOBJECTIZER_BUILD_STATIC=ON
		SOBJECTIZER_BUILD_SHARED=OFF
		SOBJECTIZER_INSTALL=ON
)

hunter_config(ZLIB
	URL "https://github.com/Telefrag-Software/zlib/archive/refs/heads/hunter-1.3.1.2.zip"
	VERSION "1.3.1.2"
	SHA1 "0a8b433ea1eac928a1dfaff3f533dfba61b3aeb9"
	CMAKE_ARGS
		ZLIB_BUILD_TESTING=OFF
		ZLIB_BUILD_SHARED=OFF
		ZLIB_BUILD_STATIC=ON
		ZLIB_BUILD_MINIZIP=OFF
		ZLIB_INSTALL=ON
		ZLIB_PREFIX=OFF
		ZLIB_INSTALL_DOCS=OFF
		ZLIB_INSTALL_LICENSES=OFF
)

hunter_config(OpenSSL
	VERSION "3.5.1"
)
